services:
  # 1. Backend Service (ASP.NET Core)
  - type: web
    name: mirai-backend
    env: docker
    rootDir: Mirai_Store
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:5185
      
      # Database
      - key: DB_DSN
        sync: false
      - key: DB_DATABASE
        value: store_game

      # Cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

      # Security & AI
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  # 2. Frontend Service (Laravel)
  - type: web
    name: mirai-frontend
    env: docker
    rootDir: Mirai_Store_FE
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://mirai-frontend-g55j.onrender.com
      - key: BACKEND_URL
        value: https://mirai-backend.onrender.com/api
      - key: VITE_BACKEND_URL
        value: https://mirai-backend.onrender.com/api
      
      # Database
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_DSN
        sync: false
      - key: DB_DATABASE
        value: store_game

      # Cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

      # AI & Security
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
